#!/bin/sh

DESTDIR="${DESTDIR:-/}"
pkglibdir="${pkglibdir:-/usr/lib/rpm}"

RPMRC="${1:-rpmrc}"
MACROS="${2:-macros}"
PLATFORM="${3:-platform}"

if grep /share/ $PLATFORM > /dev/null 2>&1 ; then
    DEFAULTDOCDIR='%{_usr}/share/doc'
else
    DEFAULTDOCDIR='%{_usr}/doc'
fi

#TEMPRC="/tmp/rpmrc.$$"
#cat << E_O_F > $TEMPRC
#include:	$RPMRC
#macrofiles:	$MACROS
#E_O_F
#
#RPM="./rpm --rcfile $TEMPRC"
RPM=rpm

arch="`$RPM --eval '%{_target_cpu}'`"
VENDOR="`$RPM --eval '%{_vendor}'`"
OS="`$RPM --eval '%{_os}'`"
RPMRC_GNU="`$RPM --eval '%{_gnu}'`"
target_platform="`$RPM --eval '%{?_gnu:%undefine _gnu}%{_target_platform}'`"
target="`$RPM --eval '%{_target}'`"

rm -f ${DESTDIR}/${pkglibdir}/noarch-${VENDOR}-${OS}
ln -s ${arch}-${VENDOR}-${OS} ${DESTDIR}/${pkglibdir}/noarch-${VENDOR}-${OS}
rm -f ${DESTDIR}/${pkglibdir}/noarch-${OS}
ln -s ${arch}-${VENDOR}-${OS} ${DESTDIR}/${pkglibdir}/noarch-${OS}

case "$arch" in
  i[3456]86|k6|athlon|pentium4) SUBSTS='s_\(i[3456]86\|k6\|athlon\|pentium4\)_i386_ s_\(i[3456]86\|k6\|athlon\|pentium4\)_i486_ s_\(i[3456]86\|k6\|athlon\|pentium4\)_i586_ s_\(i[3456]86\|k6\|athlon\|pentium4\)_i686_ s_\(i[3456]86\|k6\|athlon\|pentium4\)_k6_ s_\(i[3456]86\|k6\|athlon\|pentium4\)_athlon_ s_\(i[3456]86\|k6\|athlon\|pentium4\)_pentium4_' ;;
  alpha*) SUBSTS='s_alpha_alpha_ s_alpha_alphaev5_ s_alpha_alphaev56_ s_alpha_alphapca56_ s_alpha_alphaev6_ s_alpha_alphaev67_' ;;
  sparc*) SUBSTS='s_sparc\(64\|v9\)_sparc_ s_sparc64_sparcv9_;s_sparc\([^v]\|$\)_sparcv9\1_ s_sparcv9_sparc64_;s_sparc\([^6]\|$\)_sparc64\1_' ;;
  powerpc*|ppc*) SUBSTS='s_ppc64_ppc_ s_ppc\([^6]\|$\)_ppc64\1_' ;;
  *) SUBSTS=y___ ;;
esac
base_arch=`echo $arch | sed -e 's_i?86_i386_;s_sparc.*_sparc_;s_alpha.*_alpha_;s_\(powerpc\|ppc\).*_ppc_'`

for SUBST in $SUBSTS ; do
  ARCH=`echo $arch | sed -e $SUBST`
  TARGET_PLATFORM=`echo $target_platform | sed -e $SUBST`
  TARGET=`echo $target | sed -e $SUBST`
  LIB=lib

  PPD="${DESTDIR}/${pkglibdir}/${ARCH}-${VENDOR}-${OS}"

  [ -d $PPD ] || mkdir $PPD

  RPMRC_OPTFLAGS="`sed -n 's/^optflags: '$ARCH' //p' $RPMRC`"
  RPMRC_OPTFLAGS="`echo $RPMRC_OPTFLAGS | sed -e 's, ,\ ,g'`"

  ARCH_INSTALL_POST='%{nil}'
  MULTILIBNO=
  case "${ARCH}-${OS}" in
    sparc-linux) MULTILIBNO=1 ;;
    sparcv9-linux) MULTILIBNO=1 ;;
    sparc64-linux) ARCH_INSTALL_POST=${pkglibdir}/brp-sparc64-linux; LIB=lib64; MULTILIBNO=2 ;;
  esac

  if [ -n "$MULTILIBNO" ]; then
    MULTILIBSED='-e /^@MULTILIB/d -e s,@MULTILIBNO@,'$MULTILIBNO,
  else
    MULTILIBSED='-e /^@MULTILIBSTART@/,/^@MULTILIBEND@/d'
  fi

  case $VENDOR in
  alt)
    VENDORSED='-e s,^@alt@,,'
    ;;
  pld)
    VENDORSED='-e s,^@pld@,,'
    ;;
  mandrake)
    VENDORSED='-e s,^@mandrake@,,'
    RPMRC_OPTFLAGS="`echo $RPMRC_OPTFLAGS | sed -e s/i386/i686/`"
    ;;
  conectiva)
    VENDORSED='-e s,^@conectiva@,,'
    ;;
  redhat)
    VENDORSED='-e s,^@redhat@,,'
    ;;
  esac

  cat $PLATFORM \
  | sed -e "s,@RPMRC_OPTFLAGS@,$RPMRC_OPTFLAGS," \
	-e "s,@RPMRC_ARCH@,$ARCH," \
	-e "s,@RPMRC_GNU@,$RPMRC_GNU," \
	-e "s,@LIB@,$LIB," \
	-e "s,@ARCH_INSTALL_POST@,$ARCH_INSTALL_POST," \
	-e "s,@DEFAULTDOCDIR@,$DEFAULTDOCDIR," \
	$MULTILIBSED \
	$VENDORSED \
  | grep -v '^@' \
  > ${PPD}/macros
done

#rm $TEMPRC
