#!/bin/sh -e
#
# fixup-shared - fix permissions of libraries.
#
# $Id$
# Copyright (C) 2003, 2004  Dmitry V. Levin <ldv@altlinux.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

for file in "$@"; do
	type=`file -b "$file"` || continue
	case "$type" in
		current\ ar\ archive|*\ current\ ar\ archive)
			chmod -v u+w,a-x,ug-s "$file"
			;;
		ELF\ *\ shared\ object,\ *|*\ ELF\ *\ shared\ object,\ *)
			file_header="$(readelf -h "$file")" || continue
			entry=`printf %s "$file_header" |sed -ne 's/^ \+Entry point address: \+0x0*\([0-9a-f]\+\)$/\1/p'`
			[ -n "$entry" ] || continue

			section_header="$(readelf -S "$file")" || continue
			text=`printf %s "$section_header" |sed -ne 's/^ *\[ *[0-9]\+\] \.text \+PROGBITS \+0*\([0-9a-f]\+\) \+.*/\1/p'`
			[ -n "$text" ] || continue

			[ "$entry" != "$text" ] || chmod -v u+w,a-x,ug-s "$file"
			;;
	esac
done
