#!/bin/sh -ef
#
# fixup-pkgconfig - /usr/lib/pkgconfig/*.pc fixups.
#
# Copyright (C) 2002  Dmitry V. Levin <ldv@altlinux.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

PROG="${0##*/}"

TMPFILE="$(mktemp -t "$PROG.XXXXXXXXXX")"

exit_handler()
{
	local rc=$?
	trap '' EXIT
	rm -f -- "$TMPFILE"
	exit $rc
}

trap exit_handler SIGHUP SIGINT SIGTERM SIGQUIT SIGPIPE EXIT

: ${RPM_FIXUP_SKIPLIST:=}

fix()
{
	local fname
	fname="${f#$RPM_BUILD_ROOT}"
	fname="${fname#.}"

	# fetch parameters

	local includedir=
	local libdir=
	sed -ne "s/^\(\([a-z_]*\)\(prefix\|dir\|path\)\)=\(.*\)\$/local \1=\4/pg" "$f" >"$TMPFILE" || return 1

	# source parameters

	[ ! -s "$TMPFILE" ] || . "$TMPFILE" || return 1

	local saved_val=
	local old_val=
	local new_val=

	while [ "$includedir" != "$saved_val" ]; do
		saved_val="$includedir"
		includedir="${includedir//\/\///}"
	done

	saved_val=
	while [ "$libdir" != "$saved_val" ]; do
		saved_val="$libdir"
		libdir="${libdir//\/\///}"
	done

	# fix cflags

	old_val=`sed -ne "s/^Cflags: \([^']*\)\$/\1/pg" "$f"` || return 1
	new_val="$old_val"

	saved_val=
	while [ "$new_val" != "$saved_val" ]; do
		saved_val="$new_val"
		new_val="${new_val//\/\///}"
	done

	saved_val=
	while [ "$new_val" != "$saved_val" ]; do
		saved_val="$new_val"
		new_val=`echo "$new_val" |sed -e 's,\(^\| \+\)-I/usr\(/local\)\?/include\($\| \+\),\1\3,g'` || return 1
	done

	if [ "$includedir" = /usr/include ]; then
		saved_val=
		while [ "$new_val" != "$saved_val" ]; do
			saved_val="$new_val"
			new_val=`echo "$new_val" |sed -e 's,\(^\| \+\)-I\${includedir}\($\| \+\),\1\2,g'` || return 1
		done
	fi

	saved_val=
	while [ "$new_val" != "$saved_val" ]; do
		saved_val="$new_val"
		new_val="${new_val//  / }"
	done
	new_val="${new_val## }"
	new_val="${new_val%% }"

	if [ "$new_val" != "$old_val" ]; then
		subst -p "s|^Cflags: .*|Cflags: $new_val|g" -- "$f" || return 1
		echo "$fname: Cflags: '$old_val' --> '$new_val'" >&2
	fi

	# fix libs

	old_val=`sed -ne "s/^Libs: \([^']*\)\$/\1/pg" "$f"` || return 1
	new_val="$old_val"

	saved_val=
	while [ "$new_val" != "$saved_val" ]; do
		saved_val="$new_val"
		new_val="${new_val//\/\///}"
	done

	saved_val=
	while [ "$new_val" != "$saved_val" ]; do
		saved_val="$new_val"
		new_val=`echo "$new_val" |sed -e 's,\(^\| \+\)-L/usr\(/local\)\?/lib\($\| \+\),\1\3,g'` &&
		new_val=`echo "$new_val" |sed -e 's,\(^\| \+\)-L\('$RPM_BUILD_ROOT'\|'$RPM_BUILD_DIR'\|/usr/lib/gcc-lib\)[^ ]*\($\| \+\),\1\3,g'` ||
		return 1
	done

	if [ "$libdir" = /usr/lib ]; then
		saved_val=
		while [ "$new_val" != "$saved_val" ]; do
			saved_val="$new_val"
			new_val=`echo "$new_val" |sed -e 's,\(^\| \+\)-L\${libdir}\($\| \+\),\1\2,g'` || return 1
		done
	fi
	saved_val=
	while [ "$new_val" != "$saved_val" ]; do
		saved_val="$new_val"
		new_val="${new_val//  / }"
	done
	new_val="${new_val## }"
	new_val="${new_val%% }"

	if [ "$new_val" != "$old_val" ]; then
		subst -p "s|^Libs: .*|Libs: $new_val|g" -- "$f" || return 1
		echo "$fname: Libs: '$old_val' --> '$new_val'" >&2
	fi
}

rc=0
for f in "$@"; do
	if [ ! -f "$f" ]; then
		echo "$PROG: $f: file unavailable" >&2
		rc=1
		continue
	fi

	if [ -n "$RPM_FIXUP_SKIPLIST" ]; then
		for skip in $RPM_FIXUP_SKIPLIST; do
			if [ -z "${f//$skip}" ]; then
				continue 2
			fi
		done
	fi

	fix
done

exit $rc
