#!/bin/sh -e
#
# fixup-binconfig - /usr/bin/*-config fixups.
#
# Copyright (C) 2002  Dmitry V. Levin <ldv@altlinux.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

PROG="${0##*/}"

: ${RPM_FIXUP_SKIPLIST:=}

rc=0
for f in "$@"; do
	if [ ! -f "$f" ]; then
		echo "$PROG: $f: file unavailable" >&2
		rc=1
		continue
	fi

	if [ -n "$RPM_FIXUP_SKIPLIST" ]; then
		for skip in $RPM_FIXUP_SKIPLIST; do
			if [ -z "${f//$skip}" ]; then
				continue 2
			fi
		done
	fi

	#
done

exit $rc
