#!/bin/sh -e
#
# Copyright (C) 2003  Dmitry V. Levin <ldv@altlinux.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

unset CDPATH ||:
PROG="${0##*/}"

case "${RPM_SCRIPTS_DEBUG:-0}" in
	0) unset RPM_SCRIPTS_DEBUG ||: ;;
	1|2) ;;
	*) RPM_SCRIPTS_DEBUG=3; set -x ;;
esac

Info()
{
	echo "${0##*/}: $*" >&2
}

Fatal()
{
	echo "${0##*/}: $*" >&2
	exit 1
}

Verbose()
{
	[ "${RPM_SCRIPTS_DEBUG:-0}" -ge 1 ] || return 0
	echo "${0##*/}: $*" >&2
}

Debug()
{
	[ "${RPM_SCRIPTS_DEBUG:-0}" -ge 2 ] || return 0
	echo "${0##*/}: $*" >&2
}

ValidateBuildRoot()
{
	[ -n "$(printf %s "$RPM_BUILD_ROOT" |tr -d ' /.')" ] ||
		Fatal "invalid \$RPM_BUILD_ROOT"
}
